@accountId = 1

### Create an account with 100 of balance
POST http://localhost:8080/api/v1/account
Content-Type: application/json

{
  "startingBalance": "100"
}

### Try to create an account with -100 of balance
POST http://localhost:8080/api/v1/account
Content-Type: application/json

{
  "startingBalance": "-100"
}

### Check the balance of an account
GET http://localhost:8080/api/v1/account/{{accountId}}/balance
Accept: application/json

### Check transaction history
GET http://localhost:8080/api/v1/account/{{accountId}}/transaction
Accept: application/json

### Create new transaction, deposit of 100
POST http://localhost:8080/api/v1/account/{{accountId}}/transaction
Content-Type: application/json

{
  "amount": "100.1",
  "type": "DEPOSIT"
}

### Create new transaction, withdrawal of 100
POST http://localhost:8080/api/v1/account/{{accountId}}/transaction
Content-Type: application/json

{
  "amount": "100",
  "type": "WITHDRAWAL"
}